name: infrastructure

on:
  push:
    branches:
      - infra

jobs:
  infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Create GCP credentials file
        run: echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp_key.json

      - name: Terraform Init
        run: terraform init 
        working-directory: ./Infra/Gke-infra

      - name: Terraform Apply
        working-directory: ./Infra/Gke-infra
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT }}
          TF_VAR_credentials_path: "/tmp/gcp_key.json"
        run: terraform apply -auto-approve 